global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "GatewayPagamentos"
    metrics_path: "/health"
    static_configs:
      - targets: ["gateway-api:8080"]

  - job_name: "CatalogoMicroservice"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["catalogo-api:3000"]
